---

# Instance provisioning
- hosts: concourse-web
  gather_facts: False
  become: False
  roles:
    - { role: openstack-select-image,  tags: [ "provision" ] }
    - { role: openstack-instance,      tags: [ "provision" ] }
    - { role: gcdns,                   tags: [ "provision" ] }

# Instance configuration
- hosts: concourse-web
  gather_facts: False
  become: True
  roles:
    - { role: common,                  tags: [ "common" ] }
    - { role: postgresql,              tags: [ "postgresql" ] }
    - { role: concourse,               tags: [ "concourse" ] }
    - { role: traefik,                 tags: [ "traefik" ] }
