---

# Instance provisioning
- hosts: graylog
  gather_facts: False
  become: False
  roles:
    - { role: openstack-select-image,  tags: [ "provision" ] }
    - { role: openstack-instance,      tags: [ "provision" ] }
    - { role: gcdns,                   tags: [ "provision" ] }

# Instance configuration
- hosts: graylog
  gather_facts: False
  become: True
  roles:
    - { role: common,                  tags: [ "common" ] }
    - { role: devenv,                  tags: [ "devenv" ] }
    - { role: oracle-java,             tags: [ "java" ] }
    - { role: graylog,                 tags: [ "graylog" ] }
