---

# Instance provisioning
- hosts: vpn
  gather_facts: False
  become: False
  roles:
    - { role: openstack-select-image,  tags: [ "provision" ] }
    - { role: openstack-instance,      tags: [ "provision" ] }
    - { role: gcdns,                   tags: [ "provision" ] }

# Instance configuration
- hosts: vpn
  gather_facts: True
  become: True
  roles:
    - { role: common,                  tags: [ "common" ] }
    - { role: wireguard,               tags: [ "wireguard" ] }
