---

- name: Create directories for Traefik
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_install_path }}"
    - "{{ traefik_install_path }}/bin"
    - "{{ traefik_install_path }}/etc"

- name: Download Traefik
  get_url:
    url: "https://github.com/containous/traefik/releases/download/{{ traefik_version }}/traefik_linux-amd64"
    checksum: "{{ traefik_checksum }}"
    dest: "{{ traefik_install_path }}/bin/traefik"
    mode: 0755

- name: Install Traefik systemd service
  template:
    src: traefik.service.j2
    dest: "/etc/systemd/system/traefik.service"
  notify:
    - Reload systemd

- name: Template configuration file
  template:
    src: traefik.conf.j2
    dest: "{{ traefik_install_path }}/etc/traefik.conf"
  notify:
    - Restart Traefik
