---

- name: Set host record in Google Cloud DNS
  connection: local
  become: False
  delegate_to: localhost
  gcp_dns_resource_record_set:
    managed_zone:
      name: "{{ gcdns_managed_zone }}"
      dnsName: "{{ gcdns_managed_zone_dns_name }}"
    name: "{{ gcdns_record_name }}"
    type: A
    target: "{{ ansible_host }}"
    ttl: 300
    auth_kind: serviceaccount
    project: "{{ lookup('env', 'GOOGLE_CLOUD_PROJECT') }}"
    service_account_file: "{{ lookup('env', 'GOOGLE_CLOUD_KEYFILE_JSON') }}"

- name: Set additional records in Google Cloud DNS
  connection: local
  become: False
  delegate_to: localhost
  gcp_dns_resource_record_set:
    managed_zone:
      name: "{{ gcdns_managed_zone }}"
      dnsName: "{{ gcdns_managed_zone_dns_name }} "
    name: "{{ item.record_name }}"
    type: "{{ item.type | default('A') }}"
    target: "{{ item.value }}"
    ttl: "{{ item.ttl | default('300') }}"
    auth_kind: serviceaccount
    project: "{{ lookup('env', 'GOOGLE_CLOUD_PROJECT') }}"
    service_account_file: "{{ lookup('env', 'GOOGLE_CLOUD_KEYFILE_JSON') }}"
  with_items: "{{ gcdns_extra_records | default([]) }}"
