---

- name: Install common apt packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ common_apt_packages }}"

- name: Install apt-cron
  apt:
    name: cron-apt
    state: latest
    update_cache: yes
    cache_valid_time: 3600
