---

- name: Install common apt packages
  apt:
    name: "{{ common_apt_packages }}"
    state: latest
    update_cache: True
    cache_valid_time: 3600
    force_apt_get: True

- name: Install apt-cron
  apt:
    name: cron-apt
    state: latest
    update_cache: True
    cache_valid_time: 3600
    force_apt_get: True
