require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|
  config.ssh.username = 'ubuntu'
  config.vm.define "javadev"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :openstack do |os|
    os.flavor             = 'm1.small'
    os.openstack_auth_url = "https://keystone.cloud.syseleven.net:5000/v2.0/tokens"
    os.username           = ENV['OS_USERNAME']
    os.password           = ENV['OS_PASSWORD']
    os.region             = ENV['OS_REGION_NAME']
    os.tenant_name        = ENV['OS_PROJECT_NAME']
    os.image              = 'imple-javadev'
    os.floating_ip_pool   = 'ext-net'
    os.security_groups    = [ 'ssh_only' ]
    os.networks           = [ 'testing' ]
  end
end
