require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|
  config.ssh.username = 'ubuntu'
  config.vm.define "devstack"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :openstack do |os|
    os.flavor             = 'm1.medium'
    os.openstack_auth_url = "https://keystone.cloud.syseleven.net:5000/v2.0/tokens"
    os.username           = ENV['OS_USERNAME']
    os.password           = ENV['OS_PASSWORD']
    os.region             = ENV['OS_REGION_NAME']
    os.tenant_name        = ENV['OS_PROJECT_NAME']
    os.image              = 'Original Ubuntu Xenial 16.04 LTS'
    os.floating_ip_pool   = 'ext-net'
    os.security_groups    = [ 'testing' ]
    os.networks           = [ 'testing' ]
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo 127.0.0.1 $(cat /etc/hostname) >> /etc/hosts
    useradd -s /bin/bash -d /opt/stack -m stack
    echo "stack ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/stack
    su - stack -c "git clone https://git.openstack.org/openstack-dev/devstack"
    chmod +t /opt/stack/devstack
    chmod 777 /opt/stack/devstack
  SHELL
  config.vm.provision "file", source: "devstack.conf", destination: "/opt/stack/devstack/local.conf"
end
